version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: tatar
      POSTGRES_PASSWORD: tatar025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: unless-stopped

volumes:
  postgres_data: